package com.bhushan.bullsandcows.main;

import java.util.Scanner;

public class GameDriver 
{
	public static void startNewGame()
	{
		System.out.println("\n\n**Starting new Game** \n"
				+ "Choose an option\n"
				+ "1. Guess a number generated by the Bulls and Cows Wizard! \n"
				+ "2. Test Wizard's smarts as he guesses your number!");
		Scanner sanner=new Scanner(System.in);
		int choice=sanner.nextInt();
		while(choice!=1 && choice!=2)
		{
			System.out.println("Sorry the Wizard only accepts two options\n"
					+ "Choose an option\n"
					+ "1. Guess a number generated by the Bulls and Cows Wizard! \n"
					+ "2. Test Wizard's smarts as he guesses your number!");
			choice=sanner.nextInt();
		}
		
		if(choice==1)
		{
			//TODO 
		}
		else
		{
			//TODO
		}
		
		
	}
	public static void runGame()
	{
		boolean runGame=true;
		Scanner sc=new Scanner(System.in);
		System.out.println("Hello!!\n"
				+ "Ready for your first game ?\n"
				+ "Ready or not Here it comes!!!");
		while(runGame)
		{
			GameDriver.startNewGame();
			System.out.println("\nGo for another round?\n"
					+ "1. Yes!!\n"
					+ "2. I am done playing.");
			int choice=sc.nextInt();
			while(choice!=1 && choice!=2)
			{
				System.out.println("Sorry the Wizard only accepts two options\n"
						+ "Choose an option\n"
						+ "Go for another round?\n"
						+"1. Yes!!\n"
						+ "2. I am done playing.");
				choice=sc.nextInt();
			}
			runGame=choice==1?true:false;
			
		}
		System.out.println("Thanks for Playing \n"
				+ "Hope you had fun!!");
		sc.close();
	}
	
	public static void main(String[] args)
	{
		GameDriver.runGame();
	}
}
